
[project]
name = "anaira-erp"
version = "0.1.0"
requires-python = ">=3.11,<3.14"

dependencies = [
    "Django>=4.2,<4.3",
    "djangorestframework>=3.14,<3.15",
    "django-environ>=0.11,<0.12",
]

[tool]
